#!/bin/bash


YNH_MAIL=$(sudo yunohost user info $user | grep "mail: " | sed s/'mail: '/''/g)
domain=$(echo $YNH_MAIL | sed s/$user'@'/''/g)

CONFIG='{
"device_name": "DEVICENAME",
"listening_port": 0,
"storage_path": "/home/LOGINNAME/.btsync",
"check_for_updates": true,
"use_upnp": true,
"download_limit": 0,
"upload_limit": 0,
"webui": {
 "listen": "0.0.0.0:PORT"
},
"shared_folders": []
}'

NGINX='location /btsyncUSERNAME/ {
        rewrite ^/btsyncUSERNAME/gui(.*) /btsyncUSERNAME$1 last;
        proxy_pass	http://127.0.0.1:PORT/gui/;
        proxy_redirect 	/gui/ /btsyncUSERNAME/;
        proxy_buffering	off;
        proxy_set_header	Host           $host;
        proxy_set_header	X-Real-IP      $remote_addr;
        subs_filter	/gui /btsyncUSERNAME;
        include	conf.d/yunohost_panel.conf.inc;
    	more_clear_input_headers	"Accept-Encoding";
}'
sudo rm /etc/nginx/conf.d/$domain.d/btsync*.conf
port=9500
for i in $(ls /home)
do
	sudo yunohost user list --json | grep -q "\"username\": \"$i\""
	if [[ $? -eq 0 ]];
	then
		port=$((port+1))
		sudo mkdir /home/$i/.sync
		sudo sh -c "echo '$CONFIG' > /home/$i/.btsync/config.json"
		sudo sed -i "s@DEVICENAME@$domain - $i@g" /home/$i/.sync/config.json
		sudo sed -i "s@LOGINNAME@$i@g" /home/$i/.sync/config.json
		sudo sed -i "s@PORT@$port@g" /home/$i/.sync/config.json
		sudo chown -R $i:$i /home/$i/.sync

		sudo sh -c "echo '$NGINX' > /etc/nginx/conf.d/$domain.d/btsync$i.conf"
		sudo sed -i "s@USERNAME@$i@g" /etc/nginx/conf.d/$domain.d/btsync$i.conf
		sudo sed -i "s@PORT@$port@g" /etc/nginx/conf.d/$domain.d/btsync$i.conf	
		
	fi
done

sudo service btsync start
sudo service nginx reload
