#!/bin/bash


# Retrieve arguments
domain=$1
path=$2
platform=$3

version="1.3.105"

# Remove trailing "/" for next commands
path=${path%/}

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a btsync
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

sudo yunohost app setting btsync platform -v $platform

sudo wget http://syncapp.bittorrent.com/$version/btsync_$platform-$version.tar.gz -O /tmp/btsync.tar.gz
sudo tar -xvf /tmp/btsync.tar.gz -C /tmp/

sudo cp /tmp/btsync /usr/bin/
sudo chmod +x /usr/bin/btsync


port=9500
for i in $(ls /home)
do
	sudo yunohost user list --json | grep -q "\"username\": \"$i\""
	if [[ $? -eq 0 ]];
	then
		sudo mkdir /home/$i/.btsync
		sudo cp ../conf/user.config.json /home/$i/.btsync/config.json
		sudo sed -i "s@DEVICENAME@$domain - $i@g" /home/$i/.btsync/config.json
		sudo sed -i "s@LOGINNAME@$i@g" /home/$i/.btsync/config.json
		port=$((port+1))
		sudo sed -i "s@PORT@$port@g" /home/$i/.btsync/config.json
		sudo chown -R $i /home/$i/.btsync
		sudo cp ../conf/userUSER.conf /etc/nginx/conf.d/$domain.d/btsync$i.conf
		sudo sed -i "s@USERNAME@$i@g" /etc/nginx/conf.d/$domain.d/btsync$i.conf
		sudo sed -i "s@PORT@$port@g" /etc/nginx/conf.d/$domain.d/btsync$i.conf	
	fi
done
sudo chown -R www-data:www-data /var/www/btsync/

sudo cp ../conf/init.btsync /etc/init.d/btsync
sudo chmod +x /etc/init.d/btsync


sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@/var/www/btsync/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/btsync.conf

sudo update-rc.d btsync defaults

sudo yunohost service add btsync


# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf
