#!/bin/bash


# Retrieve arguments
domain=$1
path=$2
platform=$3

version="1.3.105"

# Remove trailing "/" for next commands
path=${path%/}

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a btsync
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

sudo yunohost app setting btsync platform -v $platform

sudo wget http://syncapp.bittorrent.com/$version/btsync_$platform-$version.tar.gz -O /tmp/btsync.tar.gz
sudo tar -xvf /tmp/btsync.tar.gz -C /tmp/

sudo cp /tmp/btsync /usr/bin/
sudo chmod +x /usr/bin/btsync

NGINX='location /btsyncUSERNAME/ {
        rewrite ^/btsyncUSERNAME/gui(.*) /btsyncUSERNAME$1 last;
        proxy_pass	http://127.0.0.1:PORT/gui/;
        proxy_redirect 	/gui/ /btsyncUSERNAME/;
        proxy_buffering	off;
        proxy_set_header	Host           $host;
        proxy_set_header	X-Real-IP      $remote_addr;
        subs_filter	/gui /btsyncUSERNAME;
        include	conf.d/yunohost_panel.conf.inc;
    	more_clear_input_headers	"Accept-Encoding";
}'
port=9500
for i in $(ls /home)
do
	sudo yunohost user list --json | grep -q "\"username\": \"$i\""
	if [[ $? -eq 0 ]];
	then
		sudo mkdir -p /home/yunohost.app/btsync/$i/
		sudo cp ../conf/user.config.json /home/yunohost.app/btsync/$i/config.json
		sudo sed -i "s@DEVICENAME@$domain - $i@g" /home/yunohost.app/btsync/$i/config.json
		sudo sed -i "s@LOGINNAME@$i@g" /home/yunohost.app/btsync/$i/config.json
		port=$((port+1))
		sudo sed -i "s@PORT@$port@g" /home/yunohost.app/btsync/$i/config.json
		sudo chown -R $i /home/yunohost.app/btsync/$i/
		
		sudo sh -c "echo '$NGINX' > /etc/nginx/conf.d/$domain.d/btsync$i.conf"
		sudo sed -i "s@USERNAME@$i@g" /etc/nginx/conf.d/$domain.d/btsync$i.conf
		sudo sed -i "s@PORT@$port@g" /etc/nginx/conf.d/$domain.d/btsync$i.conf	
	fi
done


sudo cp ../conf/init.btsync /etc/init.d/btsync
sudo chmod +x /etc/init.d/btsync


sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@/var/www/btsync/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/btsync.conf

sudo update-rc.d btsync defaults

sudo yunohost service add btsync

sudo service btsync start
# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf
