#!/bin/bash
domain=$(sudo yunohost app setting btsync domain)
sudo rm -f "/etc/nginx/conf.d/$domain.d/btsync*.conf"
sudo rm -r /home/yunohost.app/btsync/
sudo yunohost service remove btsync
sudo update-rc.d btsync remove
sudo service nginx reload
