#!/bin/bash

domain=$(sudo yunohost app setting btsync domain)
sudo apt-get remove --purge webmin
sudo rm -f /etc/nginx/conf.d/$domain.d/btsync.conf



sudo rm -rf /var/www/btsync

for i in $(ls /home)
do
	sudo yunohost user list --json | grep -q "\"username\": \"$i\""
	if [[ $? -eq 0 ]];
	then
		sudo rm -r /home/$i/.sync
	fi
done

sudo service nginx reload
